MissionControl\Bundle\UserBundle\Entity\User:
    #getters:
    #    passwordCheck:
    #        - "False": { message: "Entered password and confirmation do not match."}
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: "The username provided is already in use."
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: email
            message: "The email provided is already in use."
    properties:
        username:
            - NotNull:
                message: "Please enter the username you want to use."
            - Length:
                min: 4
                max: 12
                minMessage: "Username must have a minimum of {{ limit }} characters."
                maxMessage: "Username must have a maximum of {{ limit }} characters."
        email:
            - NotNull:
                message: "Please enter your email."
            - Email:
                message: "The email {{ value }} is not a valid email."
        password:
            - NotNull:
                message: "Password should be between 6 and 18 characters length containing at least one letter and one number."
            #- EqualTo:
            #    value: 
            #    message: "Entered password and confirmation do not match."
            - Regex: 
                pattern: "/^(?=.*\d)(?=.*[a-zA-Z]).{6,18}$/"
                message: "Password should be between 6 and 18 characters length containing at least one letter and one number."